---
# src: https://raw.githubusercontent.com/dj95/zjstatus/main/.github/workflows/release.yml

name: 'Build and Publish'
on:
  push:
    branches:
      - '*'
    tags:
      - 'v?[0-9]+.*'

permissions:
  contents: write

jobs:
  build-release:
    name: build-release
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: '1.83.0'
          target: wasm32-wasip1

      - name: Build release binary
        run: cargo build --release

      - if: >
          github.ref_type == 'tag'
        name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: false
          files: |
            ./target/wasm32-wasip1/release/zellij-autolock.wasm
